package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the PERSONNE_A_CHARGE table.
 * Do not modify this class because it will be overwritten if the configuration
 * file related to this class is modified.
 * 
 * @hibernate.class table="PERSONNE_A_CHARGE"
 */
public abstract class BasePersonneACharge implements Serializable {

	public static String PROP_ID_SALARIE = "IdSalarie";
	public static String PROP_DATE_NAISSANCE = "DateNaissance";
	public static String PROP_NOM = "Nom";
	public static String PROP_PRENOM = "Prenom";
	public static String PROP_ID = "Id";
	public static String PROP_LIEN_PARENTE = "LienParente";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _nom;
	private java.lang.String _prenom;
	private java.lang.String _lienParente;
	private java.util.Date _dateNaissance;

	// many to one
	private com.cci.gpec.db.Salarie salarie;

	// constructors
	public BasePersonneACharge() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePersonneACharge(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_PERSONNE_A_CHARGE"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: NOM
	 */
	public java.lang.String getNom() {
		return _nom;
	}

	/**
	 * Set the value related to the column: NOM
	 * 
	 * @param _nom
	 *            the NOM value
	 */
	public void setNom(java.lang.String _nom) {
		this._nom = _nom;
	}

	/**
	 * Return the value associated with the column: PRENOM
	 */
	public java.lang.String getPrenom() {
		return _prenom;
	}

	/**
	 * Set the value related to the column: PRENOM
	 * 
	 * @param _prenom
	 *            the PRENOM value
	 */
	public void setPrenom(java.lang.String _prenom) {
		this._prenom = _prenom;
	}

	/**
	 * Return the value associated with the column: LIEN_PARENTE
	 */
	public java.lang.String getLienParente() {
		return _lienParente;
	}

	/**
	 * Set the value related to the column: LIEN_PARENTE
	 * 
	 * @param _lienParente
	 *            the LIEN_PARENTE value
	 */
	public void setLienParente(java.lang.String _lienParente) {
		this._lienParente = _lienParente;
	}

	/**
	 * Return the value associated with the column: DATE_NAISSANCE
	 */
	public java.util.Date getDateNaissance() {
		return _dateNaissance;
	}

	/**
	 * Set the value related to the column: DATE_NAISSANCE
	 * 
	 * @param _dateNaissance
	 *            the DATE_NAISSANCE value
	 */
	public void setDateNaissance(java.util.Date _dateNaissance) {
		this._dateNaissance = _dateNaissance;
	}

	/**
	 * @hibernate.property column=ID_SALARIE
	 */
	public com.cci.gpec.db.Salarie getSalarie() {
		return this.salarie;
	}

	/**
	 * Set the value related to the column: ID_SALARIE
	 * 
	 * @param _idSalarie
	 *            the ID_SALARIE value
	 */
	public void setSalarie(com.cci.gpec.db.Salarie salarie) {
		this.salarie = salarie;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BasePersonneACharge))
			return false;
		else {
			com.cci.gpec.db.base.BasePersonneACharge mObj = (com.cci.gpec.db.base.BasePersonneACharge) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

}