package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the EVENEMENT table. Do not
 * modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 * 
 * @hibernate.class table="EVENEMENT"
 */
public abstract class BaseEvenement implements Serializable {

	public static String PROP_ID_SALARIE = "IdSalarie";
	public static String PROP_COMMENTAIRE = "Commentaire";
	public static String PROP_DECISION = "Decision";
	public static String PROP_ID = "Id";
	public static String PROP_JUSTIFICATIF = "Justificatif";
	public static String PROP_DATE_EVENEMENT = "DateEvenement";
	public static String PROP_NATURE = "Nature";
	public static String PROP_INTERLOCUTEUR = "Interlocuteur";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _dateEvenement;
	private java.lang.String _commentaire;
	private java.lang.String _nature;
	private java.lang.String _decision;
	private java.lang.String _justificatif;
	private java.lang.String _interlocuteur;

	// many to one
	private com.cci.gpec.db.Salarie salarie;

	// constructors
	public BaseEvenement() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEvenement(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_EVENEMENT"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: DATE_EVENEMENT
	 */
	public java.util.Date getDateEvenement() {
		return _dateEvenement;
	}

	/**
	 * Set the value related to the column: DATE_EVENEMENT
	 * 
	 * @param _dateEntretien
	 *            the DATE_EVENEMENT value
	 */
	public void setDateEvenement(java.util.Date _dateEvenement) {
		this._dateEvenement = _dateEvenement;
	}

	/**
	 * Return the value associated with the column: COMMENTAIRE
	 */
	public java.lang.String getCommentaire() {
		return _commentaire;
	}

	/**
	 * Set the value related to the column: COMMENTAIRE
	 * 
	 * @param _commentaire
	 *            the COMMENTAIRE value
	 */
	public void setCommentaire(java.lang.String _commentaire) {
		this._commentaire = _commentaire;
	}

	/**
	 * Return the value associated with the column: NATURE
	 */
	public java.lang.String getNature() {
		return _nature;
	}

	/**
	 * Set the value related to the column: NATURE
	 * 
	 * @param _nature
	 *            the NATURE value
	 */
	public void setNature(java.lang.String _nature) {
		this._nature = _nature;
	}

	/**
	 * Return the value associated with the column: DECISION
	 */
	public java.lang.String getDecision() {
		return _decision;
	}

	/**
	 * Set the value related to the column: DECISION
	 * 
	 * @param _decision
	 *            the DECISION value
	 */
	public void setDecision(java.lang.String _decision) {
		this._decision = _decision;
	}

	/**
	 * Return the value associated with the column: JUSTIFICATIF
	 */
	public java.lang.String getJustificatif() {
		return _justificatif;
	}

	/**
	 * Set the value related to the column: JUSTIFICATIF
	 * 
	 * @param _justificatif
	 *            the JUSTIFICATIF value
	 */
	public void setJustificatif(java.lang.String _justificatif) {
		this._justificatif = _justificatif;
	}

	/**
	 * @hibernate.property column=ID_SALARIE
	 */
	public com.cci.gpec.db.Salarie getSalarie() {
		return this.salarie;
	}

	/**
	 * Set the value related to the column: ID_SALARIE
	 * 
	 * @param _idSalarie
	 *            the ID_SALARIE value
	 */
	public void setSalarie(com.cci.gpec.db.Salarie salarie) {
		this.salarie = salarie;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseEvenement))
			return false;
		else {
			com.cci.gpec.db.base.BaseEvenement mObj = (com.cci.gpec.db.base.BaseEvenement) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public java.lang.String getInterlocuteur() {
		return _interlocuteur;
	}

	public void setInterlocuteur(java.lang.String _interlocuteur) {
		this._interlocuteur = _interlocuteur;
	}

}