package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the TRANSMISSION table. Do
 * not modify this class because it will be overwritten if the configuration
 * file related to this class is modified.
 * 
 * @hibernate.class table="TRANSMISSION"
 */
public abstract class BaseTransmission implements Serializable {

	public static String PROP_DATE_TRANSMISSION = "DateTransmission";
	public static String PROP_DATE_DERNIERE_DEMANDE = "DateDerniereDemande";
	public static String PROP_ID_TRANSMISSION = "IdTransmission";
	public static String PROP_ID_GROUPE = "IdGroupe";

	// fields
	private java.util.Date _dateDerniereDemande;
	private java.util.Date _dateTransmission;
	private java.lang.Integer _id;

	// many to one
	private com.cci.gpec.db.Groupe groupe;

	// constructors
	public BaseTransmission() {
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTransmission(java.lang.Integer _id) {

		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the value associated with the column: DATE_DERNIERE_DEMANDE
	 */
	public java.util.Date getDateDerniereDemande() {
		return _dateDerniereDemande;
	}

	/**
	 * Set the value related to the column: DATE_DERNIERE_DEMANDE
	 * 
	 * @param _dateDerniereDemande
	 *            the DATE_DERNIERE_DEMANDE value
	 */
	public void setDateDerniereDemande(java.util.Date _dateDerniereDemande) {
		this._dateDerniereDemande = _dateDerniereDemande;
	}

	/**
	 * Return the value associated with the column: DATE_TRANSMISSION
	 */
	public java.util.Date getDateTransmission() {
		return _dateTransmission;
	}

	/**
	 * Set the value related to the column: DATE_TRANSMISSION
	 * 
	 * @param _dateTransmission
	 *            the DATE_TRANSMISSION value
	 */
	public void setDateTransmission(java.util.Date _dateTransmission) {
		this._dateTransmission = _dateTransmission;
	}

	/**
	 * Return the value associated with the column: ID_TRANSMISSION
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the value related to the column: ID_TRANSMISSION
	 * 
	 * @param _idTransmission
	 *            the ID_TRANSMISSION value
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
	}

	public String toString() {
		return super.toString();
	}

	public com.cci.gpec.db.Groupe getGroupe() {
		return groupe;
	}

	public void setGroupe(com.cci.gpec.db.Groupe groupe) {
		this.groupe = groupe;
	}

}