package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the ADMIN table. Do not
 * modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 * 
 * @hibernate.class table="ADMIN"
 */
public abstract class BaseAdmin implements Serializable {

	public static String PROP_LOGO = "Logo";
	public static String PROP_ID = "Id";
	public static String PROP_MIGRATION = "Migration";
	public static String PROP_ID_GROUPE = "IdGroupe";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _migration;
	private java.lang.String _logo;

	// many to one
	private com.cci.gpec.db.Groupe groupe;

	// constructors
	public BaseAdmin() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAdmin(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id column="ID_ADMIN"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: MIGRATION
	 */
	public java.lang.Integer getMigration() {
		return _migration;
	}

	/**
	 * Set the value related to the column: MIGRATION
	 * 
	 * @param _migration
	 *            the MIGRATION value
	 */
	public void setMigration(java.lang.Integer _migration) {
		this._migration = _migration;
	}

	/**
	 * Return the value associated with the column: LOGO
	 */
	public java.lang.String getLogo() {
		return _logo;
	}

	/**
	 * Set the value related to the column: LOGO
	 * 
	 * @param _logo
	 *            the LOGO value
	 */
	public void setLogo(java.lang.String _logo) {
		this._logo = _logo;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseAdmin))
			return false;
		else {
			com.cci.gpec.db.base.BaseAdmin mObj = (com.cci.gpec.db.base.BaseAdmin) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public com.cci.gpec.db.Groupe getGroupe() {
		return groupe;
	}

	public void setGroupe(com.cci.gpec.db.Groupe groupe) {
		this.groupe = groupe;
	}

}