package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the FICHEMETIER table. Do not
 * modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 * 
 * @hibernate.class table="FICHEMETIER"
 */
public abstract class BaseFicheMetier implements Serializable {

	public static String PROP_FINALITE_METIER = "FinaliteMetier";
	public static String PROP_PARTICULIARITE = "Particuliarite";
	public static String PROP_ACTIVITES_RESPONSABILITES = "ActivitesResponsabilites";
	public static String PROP_CSP_REFERENCE = "CspReference";
	public static String PROP_SAVOIR_FAIRE = "SavoirFaire";
	public static String PROP_NIVEAU_FORMATION_REQUIS = "NiveauFormationRequis";
	public static String PROP_INTITULE_METIER_TYPE = "IntituleMetierType";
	public static String PROP_SAVOIR_ETRE = "SavoirEtre";
	public static String PROP_ID = "Id";
	public static String PROP_SAVOIR = "Savoir";
	public static String PROP_JUSTIFICATIF = "Justificatif";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _finaliteMetier;
	private java.lang.String _savoirFaire;
	private java.lang.String _activitesResponsabilites;
	private java.lang.String _intituleMetierType;
	private java.lang.Integer _cspReference;
	private java.lang.String _niveauFormationRequis;
	private java.lang.String _savoirEtre;
	private java.lang.String _savoir;
	private java.lang.String _particuliarite;
	private java.lang.String justificatif;

	// many to one
	// private com.cci.gpec.db.Entreprise entreprise;
	private com.cci.gpec.db.Groupe groupe;

	// constructors
	public BaseFicheMetier() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFicheMetier(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_FICHE_METIER"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: FINALITE_METIER
	 */
	public java.lang.String getFinaliteMetier() {
		return _finaliteMetier;
	}

	/**
	 * Set the value related to the column: FINALITE_METIER
	 * 
	 * @param _finaliteMetier
	 *            the FINALITE_METIER value
	 */
	public void setFinaliteMetier(java.lang.String _finaliteMetier) {
		this._finaliteMetier = _finaliteMetier;
	}

	/**
	 * Return the value associated with the column: SAVOIR_FAIRE
	 */
	public java.lang.String getSavoirFaire() {
		return _savoirFaire;
	}

	/**
	 * Set the value related to the column: SAVOIR_FAIRE
	 * 
	 * @param _savoirFaire
	 *            the SAVOIR_FAIRE value
	 */
	public void setSavoirFaire(java.lang.String _savoirFaire) {
		this._savoirFaire = _savoirFaire;
	}

	/**
	 * Return the value associated with the column: ACTIVITES_RESPONSABILITES
	 */
	public java.lang.String getActivitesResponsabilites() {
		return _activitesResponsabilites;
	}

	/**
	 * Set the value related to the column: ACTIVITES_RESPONSABILITES
	 * 
	 * @param _activitesResponsabilites
	 *            the ACTIVITES_RESPONSABILITES value
	 */
	public void setActivitesResponsabilites(
			java.lang.String _activitesResponsabilites) {
		this._activitesResponsabilites = _activitesResponsabilites;
	}

	/**
	 * Return the value associated with the column: INTITULE_METIER_TYPE
	 */
	public java.lang.String getIntituleMetierType() {
		return _intituleMetierType;
	}

	/**
	 * Set the value related to the column: INTITULE_METIER_TYPE
	 * 
	 * @param _intituleMetierType
	 *            the INTITULE_METIER_TYPE value
	 */
	public void setIntituleMetierType(java.lang.String _intituleMetierType) {
		this._intituleMetierType = _intituleMetierType;
	}

	/**
	 * Return the value associated with the column: CSP_REFERENCE
	 */
	public java.lang.Integer getCspReference() {
		return _cspReference;
	}

	/**
	 * Set the value related to the column: CSP_REFERENCE
	 * 
	 * @param _cspReference
	 *            the CSP_REFERENCE value
	 */
	public void setCspReference(java.lang.Integer _cspReference) {
		this._cspReference = _cspReference;
	}

	/**
	 * Return the value associated with the column: NIVEAU_FORMATION_REQUIS
	 */
	public java.lang.String getNiveauFormationRequis() {
		return _niveauFormationRequis;
	}

	/**
	 * Set the value related to the column: NIVEAU_FORMATION_REQUIS
	 * 
	 * @param _niveauFormationRequis
	 *            the NIVEAU_FORMATION_REQUIS value
	 */
	public void setNiveauFormationRequis(java.lang.String _niveauFormationRequis) {
		this._niveauFormationRequis = _niveauFormationRequis;
	}

	/**
	 * Return the value associated with the column: SAVOIR_ETRE
	 */
	public java.lang.String getSavoirEtre() {
		return _savoirEtre;
	}

	/**
	 * Set the value related to the column: SAVOIR_ETRE
	 * 
	 * @param _savoirEtre
	 *            the SAVOIR_ETRE value
	 */
	public void setSavoirEtre(java.lang.String _savoirEtre) {
		this._savoirEtre = _savoirEtre;
	}

	/**
	 * Return the value associated with the column: SAVOIR
	 */
	public java.lang.String getSavoir() {
		return _savoir;
	}

	/**
	 * Set the value related to the column: SAVOIR
	 * 
	 * @param _savoir
	 *            the SAVOIR value
	 */
	public void setSavoir(java.lang.String _savoir) {
		this._savoir = _savoir;
	}

	/**
	 * Return the value associated with the column: PARTICULIARITE
	 */
	public java.lang.String getParticuliarite() {
		return _particuliarite;
	}

	/**
	 * Set the value related to the column: PARTICULIARITE
	 * 
	 * @param _particuliarite
	 *            the PARTICULIARITE value
	 */
	public void setParticuliarite(java.lang.String _particuliarite) {
		this._particuliarite = _particuliarite;
	}

	public java.lang.String getJustificatif() {
		return justificatif;
	}

	public void setJustificatif(java.lang.String justificatif) {
		this.justificatif = justificatif;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseFicheMetier))
			return false;
		else {
			com.cci.gpec.db.base.BaseFicheMetier mObj = (com.cci.gpec.db.base.BaseFicheMetier) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	// public com.cci.gpec.db.Entreprise getEntreprise() {
	// return entreprise;
	// }
	//
	// public void setEntreprise(com.cci.gpec.db.Entreprise entreprise) {
	// this.entreprise = entreprise;
	// }

	public com.cci.gpec.db.Groupe getGroupe() {
		return groupe;
	}

	public void setGroupe(com.cci.gpec.db.Groupe groupe) {
		this.groupe = groupe;
	}

}