package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the FICHEDEPOSTE table. Do
 * not modify this class because it will be overwritten if the configuration
 * file related to this class is modified.
 * 
 * @hibernate.class table="FICHEDEPOSTE"
 */
public abstract class BaseFicheDePoste implements Serializable {

	public static String PROP_ID_SALARIE = "IdSalarie";
	public static String PROP_ID_METIER_TYPE = "IdMetierType";
	public static String PROP_COMPETENCES_SPECIFIQUES = "CompetencesSpecifiques";
	public static String PROP_COMPETENCES_SPECIFIQUES_TEXTE = "CompetencesSpecifiquesTexte";
	public static String PROP_ACTIVITES_SPECIFIQUES = "ActivitesSpecifiques";
	public static String PROP_ID = "Id";
	public static String PROP_COMMENTAIRES = "Commentaires";
	public static String PROP_SAVOIR = "Savoir";
	public static String PROP_SAVOIR_FAIRE = "SavoirFaire";
	public static String PROP_SAVOIR_ETRE = "SavoirEtre";
	public static String PROP_EVALUATION_GLOBALE = "EvaluationGlobale";
	public static String PROP_MOBILITE_ENVISAGEE = "MobiliteEnvisagee";
	public static String PROP_DATE_CREATION = "DateCreation";
	public static String PROP_COMPETENCES_NOUVELLES = "CompetencesNouvelles";
	public static String PROP_COMPETENCES_NOUVELLES2 = "CompetencesNouvelles2";
	public static String PROP_COMPETENCES_NOUVELLES3 = "CompetencesNouvelles3";
	public static String PROP_COMPETENCES_NOUVELLES4 = "CompetencesNouvelles4";
	public static String PROP_COMPETENCES_NOUVELLES5 = "CompetencesNouvelles5";
	public static String PROP_DATE_MODIFICATION = "DateModification";
	public static String PROP_CATEGORIE_COMPETENCE = "CategorieCompetence";
	public static String PROP_CATEGORIE_COMPETENCE2 = "CategorieCompetence2";
	public static String PROP_CATEGORIE_COMPETENCE3 = "CategorieCompetence3";
	public static String PROP_CATEGORIE_COMPETENCE4 = "CategorieCompetence4";
	public static String PROP_CATEGORIE_COMPETENCE5 = "CategorieCompetence5";
	public static String PROP_JUSTIFICATIF = "Justificatif";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _dateModification;
	private java.lang.String _competencesSpecifiques;
	private java.lang.String _competencesSpecifiquesTexte;
	private java.lang.String _commentaires;
	private java.lang.String _savoir;
	private java.lang.String _savoirFaire;
	private java.lang.String _savoirEtre;
	private java.lang.String _evaluationGlobale;
	private java.lang.String _mobiliteEnvisagee;
	private java.util.Date _dateCreation;
	private java.lang.String _competencesNouvelles;
	private java.lang.String _competencesNouvelles2;
	private java.lang.String _competencesNouvelles3;
	private java.lang.String _competencesNouvelles4;
	private java.lang.String _competencesNouvelles5;
	private java.lang.String _activitesSpecifiques;
	private java.lang.String _categorieCompetence;
	private java.lang.String _categorieCompetence2;
	private java.lang.String _categorieCompetence3;
	private java.lang.String _categorieCompetence4;
	private java.lang.String _categorieCompetence5;
	private java.lang.String justificatif;

	// many to one
	private com.cci.gpec.db.Salarie salarie;
	private com.cci.gpec.db.FicheMetier metierType;

	// constructors
	public BaseFicheDePoste() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFicheDePoste(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_FICHE_DE_POSTE"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: DATE_MODIFICATION
	 */
	public java.util.Date getDateModification() {
		return _dateModification;
	}

	/**
	 * Set the value related to the column: DATE_MODIFICATION
	 * 
	 * @param _dateModification
	 *            the DATE_MODIFICATION value
	 */
	public void setDateModification(java.util.Date _dateModification) {
		this._dateModification = _dateModification;
	}

	/**
	 * Return the value associated with the column: COMPETENCES_SPECIFIQUES
	 */
	public java.lang.String getCompetencesSpecifiques() {
		return _competencesSpecifiques;
	}

	/**
	 * Set the value related to the column: COMPETENCES_SPECIFIQUES
	 * 
	 * @param _competencesSpecifiques
	 *            the COMPETENCES_SPECIFIQUES value
	 */
	public void setCompetencesSpecifiques(
			java.lang.String _competencesSpecifiques) {
		this._competencesSpecifiques = _competencesSpecifiques;
	}

	/**
	 * Return the value associated with the column:
	 * COMPETENCES_SPECIFIQUES_TEXTE
	 */
	public java.lang.String getCompetencesSpecifiquesTexte() {
		return _competencesSpecifiquesTexte;
	}

	/**
	 * Set the value related to the column: COMPETENCES_SPECIFIQUES_TEXTE
	 * 
	 * @param _competencesSpecifiquesTexte
	 *            the COMPETENCES_SPECIFIQUES_TEXTE value
	 */
	public void setCompetencesSpecifiquesTexte(
			java.lang.String _competencesSpecifiquesTexte) {
		this._competencesSpecifiquesTexte = _competencesSpecifiquesTexte;
	}

	/**
	 * Return the value associated with the column: COMMENTAIRES
	 */
	public java.lang.String getCommentaires() {
		return _commentaires;
	}

	/**
	 * Set the value related to the column: COMMENTAIRES
	 * 
	 * @param _commentaires
	 *            the COMMENTAIRES value
	 */
	public void setCommentaires(java.lang.String _commentaires) {
		this._commentaires = _commentaires;
	}

	/**
	 * Return the value associated with the column: DATE_CREATION
	 */
	public java.util.Date getDateCreation() {
		return _dateCreation;
	}

	/**
	 * Set the value related to the column: DATE_CREATION
	 * 
	 * @param _dateCreation
	 *            the DATE_CREATION value
	 */
	public void setDateCreation(java.util.Date _dateCreation) {
		this._dateCreation = _dateCreation;
	}

	/**
	 * Return the value associated with the column: COMPETENCES_NOUVELLES
	 */
	public java.lang.String getCompetencesNouvelles() {
		return _competencesNouvelles;
	}

	/**
	 * Set the value related to the column: COMPETENCES_NOUVELLES
	 * 
	 * @param _competencesNouvelles
	 *            the COMPETENCES_NOUVELLES value
	 */
	public void setCompetencesNouvelles(java.lang.String _competencesNouvelles) {
		this._competencesNouvelles = _competencesNouvelles;
	}

	/**
	 * Return the value associated with the column: ACTIVITES_SPECIFIQUES
	 */
	public java.lang.String getActivitesSpecifiques() {
		return _activitesSpecifiques;
	}

	/**
	 * Set the value related to the column: ACTIVITES_SPECIFIQUES
	 * 
	 * @param _activitesSpecifiques
	 *            the ACTIVITES_SPECIFIQUES value
	 */
	public void setActivitesSpecifiques(java.lang.String _activitesSpecifiques) {
		this._activitesSpecifiques = _activitesSpecifiques;
	}

	/**
	 * @hibernate.property column=ID_SALARIE
	 */
	public com.cci.gpec.db.Salarie getSalarie() {
		return this.salarie;
	}

	/**
	 * Set the value related to the column: ID_SALARIE
	 * 
	 * @param _idSalarie
	 *            the ID_SALARIE value
	 */
	public void setSalarie(com.cci.gpec.db.Salarie salarie) {
		this.salarie = salarie;
	}

	/**
	 * @hibernate.property column=ID_METIER_TYPE
	 */
	public com.cci.gpec.db.FicheMetier getMetierType() {
		return this.metierType;
	}

	/**
	 * Set the value related to the column: ID_METIER_TYPE
	 * 
	 * @param _idMetierType
	 *            the ID_METIER_TYPE value
	 */
	public void setMetierType(com.cci.gpec.db.FicheMetier metierType) {
		this.metierType = metierType;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseFicheDePoste))
			return false;
		else {
			com.cci.gpec.db.base.BaseFicheDePoste mObj = (com.cci.gpec.db.base.BaseFicheDePoste) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public java.lang.String getSavoir() {
		return this._savoir;
	}

	public void setSavoir(java.lang.String _savoir) {
		this._savoir = _savoir;
	}

	public java.lang.String getSavoirFaire() {
		return this._savoirFaire;
	}

	public void setSavoirFaire(java.lang.String faire) {
		this._savoirFaire = faire;
	}

	public java.lang.String getSavoirEtre() {
		return this._savoirEtre;
	}

	public void setSavoirEtre(java.lang.String etre) {
		this._savoirEtre = etre;
	}

	public java.lang.String getMobiliteEnvisagee() {
		return this._mobiliteEnvisagee;
	}

	public void setMobiliteEnvisagee(java.lang.String envisagee) {
		this._mobiliteEnvisagee = envisagee;
	}

	public java.lang.String getEvaluationGlobale() {
		return this._evaluationGlobale;
	}

	public void setEvaluationGlobale(java.lang.String evalGlobale) {
		this._evaluationGlobale = evalGlobale;
	}

	public java.lang.String getCategorieCompetence() {
		return _categorieCompetence;
	}

	public void setCategorieCompetence(java.lang.String competence) {
		_categorieCompetence = competence;
	}

	public java.lang.String getCompetencesNouvelles2() {
		return _competencesNouvelles2;
	}

	public void setCompetencesNouvelles2(java.lang.String nouvelles2) {
		_competencesNouvelles2 = nouvelles2;
	}

	public java.lang.String getCompetencesNouvelles3() {
		return _competencesNouvelles3;
	}

	public void setCompetencesNouvelles3(java.lang.String nouvelles3) {
		_competencesNouvelles3 = nouvelles3;
	}

	public java.lang.String getCompetencesNouvelles4() {
		return _competencesNouvelles4;
	}

	public void setCompetencesNouvelles4(java.lang.String nouvelles4) {
		_competencesNouvelles4 = nouvelles4;
	}

	public java.lang.String getCompetencesNouvelles5() {
		return _competencesNouvelles5;
	}

	public void setCompetencesNouvelles5(java.lang.String nouvelles5) {
		_competencesNouvelles5 = nouvelles5;
	}

	public java.lang.String getCategorieCompetence2() {
		return _categorieCompetence2;
	}

	public void setCategorieCompetence2(java.lang.String competence2) {
		_categorieCompetence2 = competence2;
	}

	public java.lang.String getCategorieCompetence3() {
		return _categorieCompetence3;
	}

	public void setCategorieCompetence3(java.lang.String competence3) {
		_categorieCompetence3 = competence3;
	}

	public java.lang.String getCategorieCompetence4() {
		return _categorieCompetence4;
	}

	public void setCategorieCompetence4(java.lang.String competence4) {
		_categorieCompetence4 = competence4;
	}

	public java.lang.String getCategorieCompetence5() {
		return _categorieCompetence5;
	}

	public void setCategorieCompetence5(java.lang.String competence5) {
		_categorieCompetence5 = competence5;
	}

	public java.lang.String getJustificatif() {
		return justificatif;
	}

	public void setJustificatif(java.lang.String justificatif) {
		this.justificatif = justificatif;
	}

}