package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the
 * LIEN_REMUNERATION_REVENU_COMPLEMENTAIRE table. Do not modify this class
 * because it will be overwritten if the configuration file related to this
 * class is modified.
 * 
 * @hibernate.class table="LIEN_REMUNERATION_REVENU_COMPLEMENTAIRE"
 */
public abstract class BaseLienRemunerationRevenuComplementaire implements
		Serializable {

	public static String PROP_ID_REMUNERATION = "IdRemuneration";
	public static String PROP_ID_LIEN_REMUNERATION_REVENU_COMPLEMENTAIRE = "IdLienRemunerationRevenuComplementaire";
	public static String PROP_ACTUALISATION = "Actualisation";
	public static String PROP_ID_REVENU_COMPLEMENTAIRE = "IdRevenuComplementaire";
	public static String PROP_MONTANT = "Montant";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer idLienRemunerationRevenuComplementaire;

	// fields
	private double montant;
	private double actualisation;
	private String commentaire;
	private Boolean remonteNPrec;

	// collections
	private java.util.Set revenuComplementaireSet;

	// many to one
	private com.cci.gpec.db.Remuneration remuneration;
	private com.cci.gpec.db.RevenuComplementaire revenuComplementaire;

	// constructors
	public BaseLienRemunerationRevenuComplementaire() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseLienRemunerationRevenuComplementaire(
			java.lang.Integer _idLienRemunerationRevenuComplementaire) {
		this.setIdLienRemunerationRevenuComplementaire(_idLienRemunerationRevenuComplementaire);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity"
	 *               column="ID_LIEN_REMUNERATION_REVENU_COMPLEMENTAIRE"
	 */
	public java.lang.Integer getIdLienRemunerationRevenuComplementaire() {
		return idLienRemunerationRevenuComplementaire;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _idLienRemunerationRevenuComplementaire
	 *            the new ID
	 */
	public void setIdLienRemunerationRevenuComplementaire(
			java.lang.Integer idLienRemunerationRevenuComplementaire) {
		this.idLienRemunerationRevenuComplementaire = idLienRemunerationRevenuComplementaire;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: MONTANT
	 */
	public java.lang.Double getMontant() {
		return montant;
	}

	/**
	 * Set the value related to the column: MONTANT
	 * 
	 * @param _montant
	 *            the MONTANT value
	 */
	public void setMontant(java.lang.Double montant) {
		this.montant = montant;
	}

	/**
	 * @hibernate.property column=ID_REMUNERATION not-null=true
	 */
	public com.cci.gpec.db.Remuneration getRemuneration() {
		return this.remuneration;
	}

	/**
	 * Set the value related to the column: ID_REMUNERATION
	 * 
	 * @param _idRemuneration
	 *            the ID_REMUNERATION value
	 */
	public void setRemuneration(com.cci.gpec.db.Remuneration remuneration) {
		this.remuneration = remuneration;
	}

	/**
	 * @hibernate.property column=ID_REVENU_COMPLEMENTAIRE not-null=true
	 */
	public com.cci.gpec.db.RevenuComplementaire getRevenuComplementaire() {
		return this.revenuComplementaire;
	}

	/**
	 * Set the value related to the column: ID_REVENU_COMPLEMENTAIRE
	 * 
	 * @param _idRevenuComplementaire
	 *            the ID_REVENU_COMPLEMENTAIRE value
	 */
	public void setRevenuComplementaire(
			com.cci.gpec.db.RevenuComplementaire revenuComplementaire) {
		this.revenuComplementaire = revenuComplementaire;
	}

	/**
	 * Return the value associated with the column: ACTUALISATION
	 */
	public java.lang.Double getActualisation() {
		return actualisation;
	}

	/**
	 * Set the value related to the column: ACTUALISATION
	 * 
	 * @param _actualisation
	 *            the ACTUALISATION value
	 */
	public void setActualisation(java.lang.Double actualisation) {
		this.actualisation = actualisation;
	}

	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	/**
	 * Return the value associated with the column: RevenuComplementaireSet
	 */
	public java.util.Set getRevenuComplementaireSet() {
		return this.revenuComplementaireSet;
	}

	/**
	 * Set the value related to the column: RevenuComplementaireSet
	 * 
	 * @param _revenuComplementaireSet
	 *            the RevenuComplementaireSet value
	 */
	public void setRevenuComplementaireSet(java.util.Set revenuComplementaireSet) {
		this.revenuComplementaireSet = revenuComplementaireSet;
	}

	public void addToRevenuComplementaireSet(Object obj) {
		if (null == this.revenuComplementaireSet)
			this.revenuComplementaireSet = new java.util.HashSet();
		this.revenuComplementaireSet.add(obj);
	}

	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseLienRemunerationRevenuComplementaire))
			return false;
		else {
			com.cci.gpec.db.base.BaseLienRemunerationRevenuComplementaire mObj = (com.cci.gpec.db.base.BaseLienRemunerationRevenuComplementaire) obj;
			if (null == this.getIdLienRemunerationRevenuComplementaire()
					|| null == mObj.getIdLienRemunerationRevenuComplementaire())
				return false;
			else
				return (this.getIdLienRemunerationRevenuComplementaire()
						.equals(mObj
								.getIdLienRemunerationRevenuComplementaire()));
		}
	}

	@Override
	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdLienRemunerationRevenuComplementaire())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName()
						+ ":"
						+ this.getIdLienRemunerationRevenuComplementaire()
								.hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	@Override
	public String toString() {
		return super.toString();
	}

	public Boolean getRemonteNPrec() {
		return remonteNPrec;
	}

	public void setRemonteNPrec(Boolean remonteNPrec) {
		this.remonteNPrec = remonteNPrec;
	}

}