package com.cci.gpec.db.base;

import java.io.Serializable;
import java.util.Date;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the USER table. Do not modify
 * this class because it will be overwritten if the configuration file related
 * to this class is modified.
 * 
 * @hibernate.class table="GPEC_USER"
 */
public abstract class BaseUser implements Serializable {

	public static String PROP_LOGIN = "Login";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_PROFILE = "Profile";
	public static String PROP_ID = "Id";
	public static String PROP_ID_GROUPE = "IdGroupe";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _login;
	private java.lang.String _password;
	private java.lang.String _profile;
	private String nom;
	private String prenom;
	private String telephone;
	private Date dateDemandeVersionEssai;
	private String nomEntreprise;

	private boolean evenement;
	private boolean remuneration;
	private boolean ficheDePoste;
	private boolean entretien;
	private boolean contratTravail;
	private boolean admin;
	private boolean superAdmin;

	// many to one
	private com.cci.gpec.db.Groupe groupe;

	public boolean isEvenement() {
		return evenement;
	}

	public void setEvenement(boolean evenement) {
		this.evenement = evenement;
	}

	public boolean isRemuneration() {
		return remuneration;
	}

	public void setRemuneration(boolean remuneration) {
		this.remuneration = remuneration;
	}

	public boolean isFicheDePoste() {
		return ficheDePoste;
	}

	public void setFicheDePoste(boolean ficheDePoste) {
		this.ficheDePoste = ficheDePoste;
	}

	public boolean isEntretien() {
		return entretien;
	}

	public void setEntretien(boolean entretien) {
		this.entretien = entretien;
	}

	// constructors
	public BaseUser() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUser(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_USER"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: LOGIN
	 */
	public java.lang.String getLogin() {
		return _login;
	}

	/**
	 * Set the value related to the column: LOGIN
	 * 
	 * @param _login
	 *            the LOGIN value
	 */
	public void setLogin(java.lang.String _login) {
		this._login = _login;
	}

	/**
	 * Return the value associated with the column: PASSWORD
	 */
	public java.lang.String getPassword() {
		return _password;
	}

	/**
	 * Set the value related to the column: PASSWORD
	 * 
	 * @param _password
	 *            the PASSWORD value
	 */
	public void setPassword(java.lang.String _password) {
		this._password = _password;
	}

	/**
	 * Return the value associated with the column: PROFILE
	 */
	public java.lang.String getProfile() {
		return _profile;
	}

	/**
	 * Set the value related to the column: PROFILE
	 * 
	 * @param _profile
	 *            the PROFILE value
	 */
	public void setProfile(java.lang.String _profile) {
		this._profile = _profile;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseUser))
			return false;
		else {
			com.cci.gpec.db.base.BaseUser mObj = (com.cci.gpec.db.base.BaseUser) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public boolean isAdmin() {
		return admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public boolean isContratTravail() {
		return contratTravail;
	}

	public void setContratTravail(boolean contratTravail) {
		this.contratTravail = contratTravail;
	}

	public com.cci.gpec.db.Groupe getGroupe() {
		return groupe;
	}

	public void setGroupe(com.cci.gpec.db.Groupe groupe) {
		this.groupe = groupe;
	}

	public boolean isSuperAdmin() {
		return superAdmin;
	}

	public void setSuperAdmin(boolean superAdmin) {
		this.superAdmin = superAdmin;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getDateDemandeVersionEssai() {
		return dateDemandeVersionEssai;
	}

	public void setDateDemandeVersionEssai(Date dateDemandeVersionEssai) {
		this.dateDemandeVersionEssai = dateDemandeVersionEssai;
	}

	public String getNomEntreprise() {
		return nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

}