package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the FORMATION table. Do not
 * modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 * 
 * @hibernate.class table="FORMATION"
 */
public abstract class BaseFormation implements Serializable {

	public static String PROP_ID_ABSENCE = "IdAbsence";
	public static String PROP_NOM_FORMATION = "NomFormation";
	public static String PROP_ORGANISME_FORMATINO = "OrganismeFormatino";
	public static String PROP_DIF = "Dif";
	public static String PROP_VOLUME_HORAIRE = "VolumeHoraire";
	public static String PROP_DEBUT_FORMATION = "DebutFormation";
	public static String PROP_ID_SALARIE = "IdSalarie";
	public static String PROP_ID_DOMAINE_FORMATION = "IdDomaineFormation";
	public static String PROP_FIN_FORMATION = "FinFormation";
	public static String PROP_MODE = "Mode";
	public static String PROP_ID = "Id";
	public static String PROP_NOMBRE_JOUR_OUVRE = "NombreJourOuvre";
	public static String PROP_JUSTIFICATIF = "Justificatif";
	public static String PROP_COUT_OPCA = "CoutOpca";
	public static String PROP_COUT_ENTREPRISE = "CoutEntreprise";
	public static String PROP_COUT_AUTRE = "CoutAutre";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _debutFormation;
	private java.util.Date _finFormation;
	private java.lang.String _nomFormation;
	private java.lang.String _organismeFormatino;
	private java.lang.String _mode;
	private java.lang.Integer _volumeHoraire;
	private java.lang.Integer _dif;
	private java.lang.Integer _horsDif;
	private java.lang.Double _nombreJourOuvre;
	private java.lang.String justificatif;
	private java.lang.Double coutOpca;
	private java.lang.Double coutEntreprise;
	private java.lang.Double coutAutre;

	// many to one
	private com.cci.gpec.db.Domaineformation domaineFormation;
	private com.cci.gpec.db.Salarie salarie;
	private com.cci.gpec.db.Absence absence;

	// constructors
	public BaseFormation() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFormation(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_FORMATION"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: DEBUT_FORMATION
	 */
	public java.util.Date getDebutFormation() {
		return _debutFormation;
	}

	/**
	 * Set the value related to the column: DEBUT_FORMATION
	 * 
	 * @param _debutFormation
	 *            the DEBUT_FORMATION value
	 */
	public void setDebutFormation(java.util.Date _debutFormation) {
		this._debutFormation = _debutFormation;
	}

	/**
	 * Return the value associated with the column: FIN_FORMATION
	 */
	public java.util.Date getFinFormation() {
		return _finFormation;
	}

	/**
	 * Set the value related to the column: FIN_FORMATION
	 * 
	 * @param _finFormation
	 *            the FIN_FORMATION value
	 */
	public void setFinFormation(java.util.Date _finFormation) {
		this._finFormation = _finFormation;
	}

	/**
	 * Return the value associated with the column: NOM_FORMATION
	 */
	public java.lang.String getNomFormation() {
		return _nomFormation;
	}

	/**
	 * Set the value related to the column: NOM_FORMATION
	 * 
	 * @param _nomFormation
	 *            the NOM_FORMATION value
	 */
	public void setNomFormation(java.lang.String _nomFormation) {
		this._nomFormation = _nomFormation;
	}

	/**
	 * Return the value associated with the column: ORGANISME_FORMATINO
	 */
	public java.lang.String getOrganismeFormatino() {
		return _organismeFormatino;
	}

	/**
	 * Set the value related to the column: ORGANISME_FORMATINO
	 * 
	 * @param _organismeFormatino
	 *            the ORGANISME_FORMATINO value
	 */
	public void setOrganismeFormatino(java.lang.String _organismeFormatino) {
		this._organismeFormatino = _organismeFormatino;
	}

	/**
	 * Return the value associated with the column: MODE
	 */
	public java.lang.String getMode() {
		return _mode;
	}

	/**
	 * Set the value related to the column: MODE
	 * 
	 * @param _mode
	 *            the MODE value
	 */
	public void setMode(java.lang.String _mode) {
		this._mode = _mode;
	}

	/**
	 * Return the value associated with the column: VOLUME_HORAIRE
	 */
	public java.lang.Integer getVolumeHoraire() {
		return _volumeHoraire;
	}

	/**
	 * Set the value related to the column: VOLUME_HORAIRE
	 * 
	 * @param _volumeHoraire
	 *            the VOLUME_HORAIRE value
	 */
	public void setVolumeHoraire(java.lang.Integer _volumeHoraire) {
		this._volumeHoraire = _volumeHoraire;
	}

	/**
	 * Return the value associated with the column: DIF
	 */
	public java.lang.Integer getDif() {
		return _dif;
	}

	/**
	 * Set the value related to the column: DIF
	 * 
	 * @param _dif
	 *            the DIF value
	 */
	public void setDif(java.lang.Integer _dif) {
		this._dif = _dif;
	}

	/**
	 * @hibernate.property column=ID_DOMAINE_FORMATION
	 */
	public com.cci.gpec.db.Domaineformation getDomaineFormation() {
		return this.domaineFormation;
	}

	/**
	 * Set the value related to the column: ID_DOMAINE_FORMATION
	 * 
	 * @param _idDomaineFormation
	 *            the ID_DOMAINE_FORMATION value
	 */
	public void setDomaineFormation(
			com.cci.gpec.db.Domaineformation _domaineFormation) {
		this.domaineFormation = _domaineFormation;
	}

	/**
	 * @hibernate.property column=ID_SALARIE
	 */
	public com.cci.gpec.db.Salarie getSalarie() {
		return this.salarie;
	}

	/**
	 * Set the value related to the column: ID_SALARIE
	 * 
	 * @param _idSalarie
	 *            the ID_SALARIE value
	 */
	public void setSalarie(com.cci.gpec.db.Salarie salarie) {
		this.salarie = salarie;
	}

	/**
	 * @hibernate.property column=ID_ABSENCE
	 */
	public com.cci.gpec.db.Absence getAbsence() {
		return this.absence;
	}

	/**
	 * Set the value related to the column: ID_ABSENCE
	 * 
	 * @param _idAbsence
	 *            the ID_ABSENCE value
	 */
	public void setAbsence(com.cci.gpec.db.Absence absence) {
		this.absence = absence;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseFormation))
			return false;
		else {
			com.cci.gpec.db.base.BaseFormation mObj = (com.cci.gpec.db.base.BaseFormation) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public java.lang.Double getNombreJourOuvre() {
		return this._nombreJourOuvre;
	}

	public void setNombreJourOuvre(java.lang.Double jourOuvre) {
		this._nombreJourOuvre = jourOuvre;
	}

	public java.lang.String getJustificatif() {
		return justificatif;
	}

	public void setJustificatif(java.lang.String justificatif) {
		this.justificatif = justificatif;
	}

	public java.lang.Double getCoutOpca() {
		return coutOpca;
	}

	public void setCoutOpca(java.lang.Double coutOpca) {
		this.coutOpca = coutOpca;
	}

	public java.lang.Double getCoutEntreprise() {
		return coutEntreprise;
	}

	public void setCoutEntreprise(java.lang.Double coutEntreprise) {
		this.coutEntreprise = coutEntreprise;
	}

	public java.lang.Double getCoutAutre() {
		return coutAutre;
	}

	public void setCoutAutre(java.lang.Double coutAutre) {
		this.coutAutre = coutAutre;
	}

	public java.lang.Integer getHorsDif() {
		return _horsDif;
	}

	public void setHorsDif(java.lang.Integer dif) {
		_horsDif = dif;
	}

}