package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the PIECES_JUSTIFICATIVES
 * table. Do not modify this class because it will be overwritten if the
 * configuration file related to this class is modified.
 * 
 * @hibernate.class table="PIECES_JUSTIFICATIVES"
 */
public abstract class BasePiecesJustificatives implements Serializable {

	public static String PROP_ID_SALARIE = "IdSalarie";
	public static String PROP_ATTESTAION_VISITE_MEDICALE = "AttestaionVisiteMedicale";
	public static String PROP_DIPLOMES = "Diplomes";
	public static String PROP_RIB = "Rib";
	public static String PROP_CARTE_IDENTITE = "CarteIdentite";
	public static String PROP_ATTESTATION_SECU = "AttestationSecu";
	public static String PROP_ID = "Id";
	public static String PROP_HABILITATIONS = "Habilitations";
	public static String PROP_PERMIS_CONDUIRE = "PermisConduire";
	public static String PROP_CERTIFICAT_TRAVAIL = "CertificatTravail";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private boolean _carteIdentite;
	private boolean _attestationSecu;
	private boolean _permisConduire;
	private boolean _rib;
	private boolean _diplomes;
	private boolean _certificatTravail;
	private boolean _attestaionVisiteMedicale;
	private boolean _habilitations;

	// many to one
	private com.cci.gpec.db.Salarie salarie;

	// constructors
	public BasePiecesJustificatives() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePiecesJustificatives(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity"
	 *               column="ID_PIECES_JUSTIFICATIVES"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: CARTE_IDENTITE
	 */
	public boolean isCarteIdentite() {
		return _carteIdentite;
	}

	/**
	 * Set the value related to the column: CARTE_IDENTITE
	 * 
	 * @param _carteIdentite
	 *            the CARTE_IDENTITE value
	 */
	public void setCarteIdentite(boolean _carteIdentite) {
		this._carteIdentite = _carteIdentite;
	}

	/**
	 * Return the value associated with the column: ATTESTATION_SECU
	 */
	public boolean isAttestationSecu() {
		return _attestationSecu;
	}

	/**
	 * Set the value related to the column: ATTESTATION_SECU
	 * 
	 * @param _attestationSecu
	 *            the ATTESTATION_SECU value
	 */
	public void setAttestationSecu(boolean _attestationSecu) {
		this._attestationSecu = _attestationSecu;
	}

	/**
	 * Return the value associated with the column: PERMIS_CONDUIRE
	 */
	public boolean isPermisConduire() {
		return _permisConduire;
	}

	/**
	 * Set the value related to the column: PERMIS_CONDUIRE
	 * 
	 * @param _permisConduire
	 *            the PERMIS_CONDUIRE value
	 */
	public void setPermisConduire(boolean _permisConduire) {
		this._permisConduire = _permisConduire;
	}

	/**
	 * Return the value associated with the column: RIB
	 */
	public boolean isRib() {
		return _rib;
	}

	/**
	 * Set the value related to the column: RIB
	 * 
	 * @param _rib
	 *            the RIB value
	 */
	public void setRib(boolean _rib) {
		this._rib = _rib;
	}

	/**
	 * Return the value associated with the column: DIPLOMES
	 */
	public boolean isDiplomes() {
		return _diplomes;
	}

	/**
	 * Set the value related to the column: DIPLOMES
	 * 
	 * @param _diplomes
	 *            the DIPLOMES value
	 */
	public void setDiplomes(boolean _diplomes) {
		this._diplomes = _diplomes;
	}

	/**
	 * Return the value associated with the column: CERTIFICAT_TRAVAIL
	 */
	public boolean isCertificatTravail() {
		return _certificatTravail;
	}

	/**
	 * Set the value related to the column: CERTIFICAT_TRAVAIL
	 * 
	 * @param _certificatTravail
	 *            the CERTIFICAT_TRAVAIL value
	 */
	public void setCertificatTravail(boolean _certificatTravail) {
		this._certificatTravail = _certificatTravail;
	}

	/**
	 * Return the value associated with the column: ATTESTATION_VISITE_MEDICALE
	 */
	public boolean isAttestaionVisiteMedicale() {
		return _attestaionVisiteMedicale;
	}

	/**
	 * Set the value related to the column: ATTESTATION_VISITE_MEDICALE
	 * 
	 * @param _attestaionVisiteMedicale
	 *            the ATTESTATION_VISITE_MEDICALE value
	 */
	public void setAttestaionVisiteMedicale(boolean _attestaionVisiteMedicale) {
		this._attestaionVisiteMedicale = _attestaionVisiteMedicale;
	}

	/**
	 * Return the value associated with the column: HABILITATIONS
	 */
	public boolean isHabilitations() {
		return _habilitations;
	}

	/**
	 * Set the value related to the column: HABILITATIONS
	 * 
	 * @param _habilitations
	 *            the HABILITATIONS value
	 */
	public void setHabilitations(boolean _habilitations) {
		this._habilitations = _habilitations;
	}

	/**
	 * @hibernate.property column=ID_SALARIE
	 */
	public com.cci.gpec.db.Salarie getSalarie() {
		return this.salarie;
	}

	/**
	 * Set the value related to the column: ID_SALARIE
	 * 
	 * @param _idSalarie
	 *            the ID_SALARIE value
	 */
	public void setSalarie(com.cci.gpec.db.Salarie salarie) {
		this.salarie = salarie;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BasePiecesJustificatives))
			return false;
		else {
			com.cci.gpec.db.base.BasePiecesJustificatives mObj = (com.cci.gpec.db.base.BasePiecesJustificatives) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

}