package com.cci.gpec.db.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TYPERECOURS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TYPERECOURS"
 */
public abstract class BaseTyperecours  implements Serializable {

	public static String PROP_NOM_TYPE_RECOURS = "NomTypeRecours";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _nomTypeRecours;

	// collections
	private java.util.Set _pARCOURSs;


	// constructors
	public BaseTyperecours () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTyperecours (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="ID_TYPE_RECOURS"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: NOM_TYPE_RECOURS
	 */
	public java.lang.String getNomTypeRecours () {
		return _nomTypeRecours;
	}

	/**
	 * Set the value related to the column: NOM_TYPE_RECOURS
	 * @param _nomTypeRecours the NOM_TYPE_RECOURS value
	 */
	public void setNomTypeRecours (java.lang.String _nomTypeRecours) {
		this._nomTypeRecours = _nomTypeRecours;
	}


	/**
	 * Return the value associated with the column: PARCOURSs
	 */
	public java.util.Set getPARCOURSs () {
		return this._pARCOURSs;
	}

	/**
	 * Set the value related to the column: PARCOURSs
	 * @param _pARCOURSs the PARCOURSs value
	 */
	public void setPARCOURSs (java.util.Set _pARCOURSs) {
		this._pARCOURSs = _pARCOURSs;
	}
	
	public void addToPARCOURSs (Object obj) {
		if (null == this._pARCOURSs) this._pARCOURSs = new java.util.HashSet();
		this._pARCOURSs.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseTyperecours)) return false;
		else {
			com.cci.gpec.db.base.BaseTyperecours mObj = (com.cci.gpec.db.base.BaseTyperecours) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}