package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the OBJECTIFSENTRETIEN table.
 * Do not modify this class because it will be overwritten if the configuration
 * file related to this class is modified.
 * 
 * @hibernate.class table="OBJECTIFSENTRETIEN"
 */
public abstract class BaseObjectifsentretien implements Serializable {

	public static String PROP_RESULTAT = "Resultat";
	public static String PROP_COMMENTAIRE = "Commentaire";
	public static String PROP_MOYEN = "Moyen";
	public static String PROP_DELAI = "Delai";
	public static String PROP_INTITULE = "Intitule";
	public static String PROP_ID = "Id";
	public static String PROP_ID_OBJECTIF = "IdObjectif";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer idObjectif;

	// fields
	private java.lang.String intitule;
	private java.lang.String delai;
	private java.lang.String moyen;
	private java.lang.String resultat;
	private java.lang.String commentaire;

	// many to one
	private com.cci.gpec.db.Entretien entretien;

	// constructors
	public BaseObjectifsentretien() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseObjectifsentretien(java.lang.Integer _idObjectif) {
		this.setIdObjectif(_idObjectif);
		initialize();
	}

	protected void initialize() {
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseObjectifsentretien))
			return false;
		else {
			com.cci.gpec.db.base.BaseObjectifsentretien mObj = (com.cci.gpec.db.base.BaseObjectifsentretien) obj;
			if (null == this.getIdObjectif() || null == mObj.getIdObjectif())
				return false;
			else
				return (this.getIdObjectif().equals(mObj.getIdObjectif()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdObjectif())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getIdObjectif().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public java.lang.Integer getIdObjectif() {
		return idObjectif;
	}

	public void setIdObjectif(java.lang.Integer idObjectif) {
		this.idObjectif = idObjectif;
	}

	public java.lang.String getIntitule() {
		return intitule;
	}

	public void setIntitule(java.lang.String intitule) {
		this.intitule = intitule;
	}

	public java.lang.String getDelai() {
		return delai;
	}

	public void setDelai(java.lang.String delai) {
		this.delai = delai;
	}

	public java.lang.String getMoyen() {
		return moyen;
	}

	public void setMoyen(java.lang.String moyen) {
		this.moyen = moyen;
	}

	public java.lang.String getResultat() {
		return resultat;
	}

	public void setResultat(java.lang.String resultat) {
		this.resultat = resultat;
	}

	public java.lang.String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(java.lang.String commentaire) {
		this.commentaire = commentaire;
	}

	public com.cci.gpec.db.Entretien getEntretien() {
		return entretien;
	}

	public void setEntretien(com.cci.gpec.db.Entretien entretien) {
		this.entretien = entretien;
	}

}