package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the REMUNERATION table. Do
 * not modify this class because it will be overwritten if the configuration
 * file related to this class is modified.
 * 
 * @hibernate.class table="REMUNERATION"
 */
public abstract class BaseRemuneration implements Serializable {

	public static String PROP_ID_SALARIE = "IdSalarie";
	public static String PROP_AUGMENTATION_INDIVIDUELLE_COMMENTAIRE = "AugmentationIndividuelleCommentaire";
	public static String PROP_HORAIRE_MENSUEL_TRAVAILLE = "HoraireMensuelTravaille";
	public static String PROP_HEURES_SUP25_ACTUALISATION = "HeuresSup25Actualisation";
	public static String PROP_SALAIRE_MINIMUM_CONVENTIONNEL = "SalaireMinimumConventionnel";
	public static String PROP_ID_STATUT = "IdStatut";
	public static String PROP_SALAIRE_MENSUEL_CENVENTIONNEL_BRUT = "SalaireMensuelCenventionnelBrut";
	public static String PROP_SALAIRE_DE_BASE_COMMENTAIRE = "SalaireDeBaseCommentaire";
	public static String PROP_AUGMENTATION_INDIVIDUELLE_ACTUALISATION = "AugmentationIndividuelleActualisation";
	public static String PROP_SALAIRE_MINIMUM_CONVENTIONNEL_COMMENTAIRE = "SalaireMinimumConventionnelCommentaire";
	public static String PROP_HEURES_SUP50 = "HeuresSup50";
	public static String PROP_COEFFICIENT = "Coefficient";
	public static String PROP_HEURES_SUP25_COMMENTAIRE = "HeuresSup25Commentaire";
	public static String PROP_AUGMENTATION_COLLECTIVE = "AugmentationCollective";
	public static String PROP_AUGMENTATION_INDIVIDUELLE = "AugmentationIndividuelle";
	public static String PROP_SALAIRE_MINIMUM_CONVENTIONNEL_ACTUALISATION = "SalaireMinimumConventionnelActualisation";
	public static String PROP_ECHELON = "Echelon";
	public static String PROP_COMMENTAIRE = "Commentaire";
	public static String PROP_SALAIRE_MENSUEL_BRUT = "SalaireMensuelBrut";
	public static String PROP_SALAIRE_DE_BASE_ACTUALISATION = "SalaireDeBaseActualisation";
	public static String PROP_SALAIRE_DE_BASE = "SalaireDeBase";
	public static String PROP_ID_METIER = "IdMetier";
	public static String PROP_ID_REMUNERATION = "IdRemuneration";
	public static String PROP_HEURES_SUP25 = "HeuresSup25";
	public static String PROP_AUGMENTATION_COLLECTIVE_COMMENTAIRE = "AugmentationCollectiveCommentaire";
	public static String PROP_HEURES_SUP50_COMMENTAIRE = "HeuresSup50Commentaire";
	public static String PROP_ID_REVENU_COMPLEMENTAIRE = "IdRevenuComplementaire";
	public static String PROP_HEURES_SUP50_ACTUALISATION = "HeuresSup50Actualisation";
	public static String PROP_AUGMENTATION_COLLECTIVE_ACTUALISATION = "AugmentationCollectiveActualisation";
	public static String PROP_ANNEE = "Annee";
	public static String PROP_TAUX_HORAIRE_BRUT = "TauxHoraireBrut";
	public static String PROP_NIVEAU = "Niveau";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idRemuneration;

	// fields
	private java.lang.String _heuresSup50Commentaire;
	private java.lang.Double _heuresSup50;
	private java.lang.Double _augmentationCollective;
	private java.lang.Double _salaireMensuelCenventionnelBrut;
	private java.lang.String _niveau;
	private java.lang.String _echelon;
	private java.lang.Integer _annee;
	private java.lang.Double _salaireMinimumConventionnelActualisation;
	private java.lang.Double _augmentationCollectiveActualisation;
	private java.lang.Double _salaireDeBaseActualisation;
	private java.lang.String _horaireMensuelTravaille;
	private java.lang.Integer _idMetier;
	private java.lang.String _salaireMinimumConventionnelCommentaire;
	private java.lang.Double _salaireDeBase;
	private java.lang.String _salaireDeBaseCommentaire;
	private java.lang.Double _heuresSup25Actualisation;
	private java.lang.String _commentaire;
	private java.lang.Double _augmentationIndividuelle;
	private java.lang.Double _heuresSup25;
	private java.lang.Double _heuresSup50Actualisation;
	private java.lang.Integer _idStatut;
	private java.lang.Double _tauxHoraireBrut;
	private java.lang.Double _augmentationIndividuelleActualisation;
	private java.lang.String _augmentationIndividuelleCommentaire;
	private java.lang.String _coefficient;
	private java.lang.Integer _idRevenuComplementaire;
	private java.lang.String _heuresSup25Commentaire;
	private java.lang.Double _salaireMinimumConventionnel;
	private java.lang.String _augmentationCollectiveCommentaire;
	private java.lang.Double _salaireMensuelBrut;
	private Double baseBruteAnnuelle;
	private Double remuGlobale;
	private Double heuresSupAnnuelles;
	private Double avantagesNonAssujettisAnnuels;

	// many to one
	private com.cci.gpec.db.Salarie salarie;

	// collections
	private java.util.Set _lienRemunerationRevenuComplementaireSet;

	// constructors
	public BaseRemuneration() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseRemuneration(java.lang.Integer _idRemuneration) {
		this.setIdRemuneration(_idRemuneration);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_REMUNERATION"
	 */
	public java.lang.Integer getIdRemuneration() {
		return _idRemuneration;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _idRemuneration
	 *            the new ID
	 */
	public void setIdRemuneration(java.lang.Integer _idRemuneration) {
		this._idRemuneration = _idRemuneration;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: HEURES_SUP_50_COMMENTAIRE
	 */
	public java.lang.String getHeuresSup50Commentaire() {
		return _heuresSup50Commentaire;
	}

	/**
	 * Set the value related to the column: HEURES_SUP_50_COMMENTAIRE
	 * 
	 * @param _heuresSup50Commentaire
	 *            the HEURES_SUP_50_COMMENTAIRE value
	 */
	public void setHeuresSup50Commentaire(
			java.lang.String _heuresSup50Commentaire) {
		this._heuresSup50Commentaire = _heuresSup50Commentaire;
	}

	/**
	 * Return the value associated with the column: HEURES_SUP_50
	 */
	public java.lang.Double getHeuresSup50() {
		return _heuresSup50;
	}

	/**
	 * Set the value related to the column: HEURES_SUP_50
	 * 
	 * @param _heuresSup50
	 *            the HEURES_SUP_50 value
	 */
	public void setHeuresSup50(java.lang.Double _heuresSup50) {
		this._heuresSup50 = _heuresSup50;
	}

	/**
	 * Return the value associated with the column: AUGMENTATION_COLLECTIVE
	 */
	public java.lang.Double getAugmentationCollective() {
		return _augmentationCollective;
	}

	/**
	 * Set the value related to the column: AUGMENTATION_COLLECTIVE
	 * 
	 * @param _augmentationCollective
	 *            the AUGMENTATION_COLLECTIVE value
	 */
	public void setAugmentationCollective(
			java.lang.Double _augmentationCollective) {
		this._augmentationCollective = _augmentationCollective;
	}

	/**
	 * Return the value associated with the column:
	 * SALAIRE_MENSUEL_CENVENTIONNEL_BRUT
	 */
	public java.lang.Double getSalaireMensuelCenventionnelBrut() {
		return _salaireMensuelCenventionnelBrut;
	}

	/**
	 * Set the value related to the column: SALAIRE_MENSUEL_CENVENTIONNEL_BRUT
	 * 
	 * @param _salaireMensuelCenventionnelBrut
	 *            the SALAIRE_MENSUEL_CENVENTIONNEL_BRUT value
	 */
	public void setSalaireMensuelCenventionnelBrut(
			java.lang.Double _salaireMensuelCenventionnelBrut) {
		this._salaireMensuelCenventionnelBrut = _salaireMensuelCenventionnelBrut;
	}

	/**
	 * Return the value associated with the column: NIVEAU
	 */
	public java.lang.String getNiveau() {
		return _niveau;
	}

	/**
	 * Set the value related to the column: NIVEAU
	 * 
	 * @param _niveau
	 *            the NIVEAU value
	 */
	public void setNiveau(java.lang.String _niveau) {
		this._niveau = _niveau;
	}

	/**
	 * Return the value associated with the column: ECHELON
	 */
	public java.lang.String getEchelon() {
		return _echelon;
	}

	/**
	 * Set the value related to the column: ECHELON
	 * 
	 * @param _echelon
	 *            the ECHELON value
	 */
	public void setEchelon(java.lang.String _echelon) {
		this._echelon = _echelon;
	}

	/**
	 * Return the value associated with the column: ANNEE
	 */
	public java.lang.Integer getAnnee() {
		return _annee;
	}

	/**
	 * Set the value related to the column: ANNEE
	 * 
	 * @param _annee
	 *            the ANNEE value
	 */
	public void setAnnee(java.lang.Integer _annee) {
		this._annee = _annee;
	}

	/**
	 * Return the value associated with the column:
	 * SALAIRE_MINIMUM_CONVENTIONNEL_ACTUALISATION
	 */
	public java.lang.Double getSalaireMinimumConventionnelActualisation() {
		return _salaireMinimumConventionnelActualisation;
	}

	/**
	 * Set the value related to the column:
	 * SALAIRE_MINIMUM_CONVENTIONNEL_ACTUALISATION
	 * 
	 * @param _salaireMinimumConventionnelActualisation
	 *            the SALAIRE_MINIMUM_CONVENTIONNEL_ACTUALISATION value
	 */
	public void setSalaireMinimumConventionnelActualisation(
			java.lang.Double _salaireMinimumConventionnelActualisation) {
		this._salaireMinimumConventionnelActualisation = _salaireMinimumConventionnelActualisation;
	}

	/**
	 * Return the value associated with the column:
	 * AUGMENTATION_COLLECTIVE_ACTUALISATION
	 */
	public java.lang.Double getAugmentationCollectiveActualisation() {
		return _augmentationCollectiveActualisation;
	}

	/**
	 * Set the value related to the column:
	 * AUGMENTATION_COLLECTIVE_ACTUALISATION
	 * 
	 * @param _augmentationCollectiveActualisation
	 *            the AUGMENTATION_COLLECTIVE_ACTUALISATION value
	 */
	public void setAugmentationCollectiveActualisation(
			java.lang.Double _augmentationCollectiveActualisation) {
		this._augmentationCollectiveActualisation = _augmentationCollectiveActualisation;
	}

	/**
	 * Return the value associated with the column:
	 * SALAIRE_DE_BASE_ACTUALISATION
	 */
	public java.lang.Double getSalaireDeBaseActualisation() {
		return _salaireDeBaseActualisation;
	}

	/**
	 * Set the value related to the column: SALAIRE_DE_BASE_ACTUALISATION
	 * 
	 * @param _salaireDeBaseActualisation
	 *            the SALAIRE_DE_BASE_ACTUALISATION value
	 */
	public void setSalaireDeBaseActualisation(
			java.lang.Double _salaireDeBaseActualisation) {
		this._salaireDeBaseActualisation = _salaireDeBaseActualisation;
	}

	/**
	 * Return the value associated with the column: HORAIRE_MENSUEL_TRAVAILLE
	 */
	public java.lang.String getHoraireMensuelTravaille() {
		return _horaireMensuelTravaille;
	}

	/**
	 * Set the value related to the column: HORAIRE_MENSUEL_TRAVAILLE
	 * 
	 * @param _horaireMensuelTravaille
	 *            the HORAIRE_MENSUEL_TRAVAILLE value
	 */
	public void setHoraireMensuelTravaille(
			java.lang.String _horaireMensuelTravaille) {
		this._horaireMensuelTravaille = _horaireMensuelTravaille;
	}

	/**
	 * Return the value associated with the column: ID_METIER
	 */
	public java.lang.Integer getIdMetier() {
		return _idMetier;
	}

	/**
	 * Set the value related to the column: ID_METIER
	 * 
	 * @param _idMetier
	 *            the ID_METIER value
	 */
	public void setIdMetier(java.lang.Integer _idMetier) {
		this._idMetier = _idMetier;
	}

	/**
	 * Return the value associated with the column:
	 * SALAIRE_MINIMUM_CONVENTIONNEL_COMMENTAIRE
	 */
	public java.lang.String getSalaireMinimumConventionnelCommentaire() {
		return _salaireMinimumConventionnelCommentaire;
	}

	/**
	 * Set the value related to the column:
	 * SALAIRE_MINIMUM_CONVENTIONNEL_COMMENTAIRE
	 * 
	 * @param _salaireMinimumConventionnelCommentaire
	 *            the SALAIRE_MINIMUM_CONVENTIONNEL_COMMENTAIRE value
	 */
	public void setSalaireMinimumConventionnelCommentaire(
			java.lang.String _salaireMinimumConventionnelCommentaire) {
		this._salaireMinimumConventionnelCommentaire = _salaireMinimumConventionnelCommentaire;
	}

	/**
	 * Return the value associated with the column: SALAIRE_DE_BASE
	 */
	public java.lang.Double getSalaireDeBase() {
		return _salaireDeBase;
	}

	/**
	 * Set the value related to the column: SALAIRE_DE_BASE
	 * 
	 * @param _salaireDeBase
	 *            the SALAIRE_DE_BASE value
	 */
	public void setSalaireDeBase(java.lang.Double _salaireDeBase) {
		this._salaireDeBase = _salaireDeBase;
	}

	/**
	 * Return the value associated with the column: SALAIRE_DE_BASE_COMMENTAIRE
	 */
	public java.lang.String getSalaireDeBaseCommentaire() {
		return _salaireDeBaseCommentaire;
	}

	/**
	 * Set the value related to the column: SALAIRE_DE_BASE_COMMENTAIRE
	 * 
	 * @param _salaireDeBaseCommentaire
	 *            the SALAIRE_DE_BASE_COMMENTAIRE value
	 */
	public void setSalaireDeBaseCommentaire(
			java.lang.String _salaireDeBaseCommentaire) {
		this._salaireDeBaseCommentaire = _salaireDeBaseCommentaire;
	}

	/**
	 * Return the value associated with the column: HEURES_SUP_25_ACTUALISATION
	 */
	public java.lang.Double getHeuresSup25Actualisation() {
		return _heuresSup25Actualisation;
	}

	/**
	 * Set the value related to the column: HEURES_SUP_25_ACTUALISATION
	 * 
	 * @param _heuresSup25Actualisation
	 *            the HEURES_SUP_25_ACTUALISATION value
	 */
	public void setHeuresSup25Actualisation(
			java.lang.Double _heuresSup25Actualisation) {
		this._heuresSup25Actualisation = _heuresSup25Actualisation;
	}

	/**
	 * Return the value associated with the column: COMMENTAIRE
	 */
	public java.lang.String getCommentaire() {
		return _commentaire;
	}

	/**
	 * Set the value related to the column: COMMENTAIRE
	 * 
	 * @param _commentaire
	 *            the COMMENTAIRE value
	 */
	public void setCommentaire(java.lang.String _commentaire) {
		this._commentaire = _commentaire;
	}

	/**
	 * @hibernate.property column=ID_SALARIE not-null=true
	 */
	public com.cci.gpec.db.Salarie getSalarie() {
		return this.salarie;
	}

	/**
	 * Set the value related to the column: ID_SALARIE
	 * 
	 * @param _idSalarie
	 *            the ID_SALARIE value
	 */
	public void setSalarie(com.cci.gpec.db.Salarie salarie) {
		this.salarie = salarie;
	}

	/**
	 * Return the value associated with the column: AUGMENTATION_INDIVIDUELLE
	 */
	public java.lang.Double getAugmentationIndividuelle() {
		return _augmentationIndividuelle;
	}

	/**
	 * Set the value related to the column: AUGMENTATION_INDIVIDUELLE
	 * 
	 * @param _augmentationIndividuelle
	 *            the AUGMENTATION_INDIVIDUELLE value
	 */
	public void setAugmentationIndividuelle(
			java.lang.Double _augmentationIndividuelle) {
		this._augmentationIndividuelle = _augmentationIndividuelle;
	}

	/**
	 * Return the value associated with the column: HEURES_SUP_25
	 */
	public java.lang.Double getHeuresSup25() {
		return _heuresSup25;
	}

	/**
	 * Set the value related to the column: HEURES_SUP_25
	 * 
	 * @param _heuresSup25
	 *            the HEURES_SUP_25 value
	 */
	public void setHeuresSup25(java.lang.Double _heuresSup25) {
		this._heuresSup25 = _heuresSup25;
	}

	/**
	 * Return the value associated with the column: HEURES_SUP_50_ACTUALISATION
	 */
	public java.lang.Double getHeuresSup50Actualisation() {
		return _heuresSup50Actualisation;
	}

	/**
	 * Set the value related to the column: HEURES_SUP_50_ACTUALISATION
	 * 
	 * @param _heuresSup50Actualisation
	 *            the HEURES_SUP_50_ACTUALISATION value
	 */
	public void setHeuresSup50Actualisation(
			java.lang.Double _heuresSup50Actualisation) {
		this._heuresSup50Actualisation = _heuresSup50Actualisation;
	}

	/**
	 * Return the value associated with the column: ID_STATUT
	 */
	public java.lang.Integer getIdStatut() {
		return _idStatut;
	}

	/**
	 * Set the value related to the column: ID_STATUT
	 * 
	 * @param _idStatut
	 *            the ID_STATUT value
	 */
	public void setIdStatut(java.lang.Integer _idStatut) {
		this._idStatut = _idStatut;
	}

	/**
	 * Return the value associated with the column: TAUX_HORAIRE_BRUT
	 */
	public java.lang.Double getTauxHoraireBrut() {
		return _tauxHoraireBrut;
	}

	/**
	 * Set the value related to the column: TAUX_HORAIRE_BRUT
	 * 
	 * @param _tauxHoraireBrut
	 *            the TAUX_HORAIRE_BRUT value
	 */
	public void setTauxHoraireBrut(java.lang.Double _tauxHoraireBrut) {
		this._tauxHoraireBrut = _tauxHoraireBrut;
	}

	/**
	 * Return the value associated with the column:
	 * AUGMENTATION_INDIVIDUELLE_ACTUALISATION
	 */
	public java.lang.Double getAugmentationIndividuelleActualisation() {
		return _augmentationIndividuelleActualisation;
	}

	/**
	 * Set the value related to the column:
	 * AUGMENTATION_INDIVIDUELLE_ACTUALISATION
	 * 
	 * @param _augmentationIndividuelleActualisation
	 *            the AUGMENTATION_INDIVIDUELLE_ACTUALISATION value
	 */
	public void setAugmentationIndividuelleActualisation(
			java.lang.Double _augmentationIndividuelleActualisation) {
		this._augmentationIndividuelleActualisation = _augmentationIndividuelleActualisation;
	}

	/**
	 * Return the value associated with the column:
	 * AUGMENTATION_INDIVIDUELLE_COMMENTAIRE
	 */
	public java.lang.String getAugmentationIndividuelleCommentaire() {
		return _augmentationIndividuelleCommentaire;
	}

	/**
	 * Set the value related to the column:
	 * AUGMENTATION_INDIVIDUELLE_COMMENTAIRE
	 * 
	 * @param _augmentationIndividuelleCommentaire
	 *            the AUGMENTATION_INDIVIDUELLE_COMMENTAIRE value
	 */
	public void setAugmentationIndividuelleCommentaire(
			java.lang.String _augmentationIndividuelleCommentaire) {
		this._augmentationIndividuelleCommentaire = _augmentationIndividuelleCommentaire;
	}

	/**
	 * Return the value associated with the column: COEFFICIENT
	 */
	public java.lang.String getCoefficient() {
		return _coefficient;
	}

	/**
	 * Set the value related to the column: COEFFICIENT
	 * 
	 * @param _coefficient
	 *            the COEFFICIENT value
	 */
	public void setCoefficient(java.lang.String _coefficient) {
		this._coefficient = _coefficient;
	}

	/**
	 * Return the value associated with the column: ID_REVENU_COMPLEMENTAIRE
	 */
	public java.lang.Integer getIdRevenuComplementaire() {
		return _idRevenuComplementaire;
	}

	/**
	 * Set the value related to the column: ID_REVENU_COMPLEMENTAIRE
	 * 
	 * @param _idRevenuComplementaire
	 *            the ID_REVENU_COMPLEMENTAIRE value
	 */
	public void setIdRevenuComplementaire(
			java.lang.Integer _idRevenuComplementaire) {
		this._idRevenuComplementaire = _idRevenuComplementaire;
	}

	/**
	 * Return the value associated with the column: HEURES_SUP_25_COMMENTAIRE
	 */
	public java.lang.String getHeuresSup25Commentaire() {
		return _heuresSup25Commentaire;
	}

	/**
	 * Set the value related to the column: HEURES_SUP_25_COMMENTAIRE
	 * 
	 * @param _heuresSup25Commentaire
	 *            the HEURES_SUP_25_COMMENTAIRE value
	 */
	public void setHeuresSup25Commentaire(
			java.lang.String _heuresSup25Commentaire) {
		this._heuresSup25Commentaire = _heuresSup25Commentaire;
	}

	/**
	 * Return the value associated with the column:
	 * SALAIRE_MINIMUM_CONVENTIONNEL
	 */
	public java.lang.Double getSalaireMinimumConventionnel() {
		return _salaireMinimumConventionnel;
	}

	/**
	 * Set the value related to the column: SALAIRE_MINIMUM_CONVENTIONNEL
	 * 
	 * @param _salaireMinimumConventionnel
	 *            the SALAIRE_MINIMUM_CONVENTIONNEL value
	 */
	public void setSalaireMinimumConventionnel(
			java.lang.Double _salaireMinimumConventionnel) {
		this._salaireMinimumConventionnel = _salaireMinimumConventionnel;
	}

	/**
	 * Return the value associated with the column:
	 * AUGMENTATION_COLLECTIVE_COMMENTAIRE
	 */
	public java.lang.String getAugmentationCollectiveCommentaire() {
		return _augmentationCollectiveCommentaire;
	}

	/**
	 * Set the value related to the column: AUGMENTATION_COLLECTIVE_COMMENTAIRE
	 * 
	 * @param _augmentationCollectiveCommentaire
	 *            the AUGMENTATION_COLLECTIVE_COMMENTAIRE value
	 */
	public void setAugmentationCollectiveCommentaire(
			java.lang.String _augmentationCollectiveCommentaire) {
		this._augmentationCollectiveCommentaire = _augmentationCollectiveCommentaire;
	}

	/**
	 * Return the value associated with the column: SALAIRE_MENSUEL_BRUT
	 */
	public java.lang.Double getSalaireMensuelBrut() {
		return _salaireMensuelBrut;
	}

	/**
	 * Set the value related to the column: SALAIRE_MENSUEL_BRUT
	 * 
	 * @param _salaireMensuelBrut
	 *            the SALAIRE_MENSUEL_BRUT value
	 */
	public void setSalaireMensuelBrut(java.lang.Double _salaireMensuelBrut) {
		this._salaireMensuelBrut = _salaireMensuelBrut;
	}

	/**
	 * Return the value associated with the column:
	 * LienRemunerationRevenuComplementaireSet
	 */
	public java.util.Set getLienRemunerationRevenuComplementaireSet() {
		return this._lienRemunerationRevenuComplementaireSet;
	}

	/**
	 * Set the value related to the column:
	 * LienRemunerationRevenuComplementaireSet
	 * 
	 * @param _lienRemunerationRevenuComplementaireSet
	 *            the LienRemunerationRevenuComplementaireSet value
	 */
	public void setLienRemunerationRevenuComplementaireSet(
			java.util.Set _lienRemunerationRevenuComplementaireSet) {
		this._lienRemunerationRevenuComplementaireSet = _lienRemunerationRevenuComplementaireSet;
	}

	public void addToLienRemunerationRevenuComplementaireSet(Object obj) {
		if (null == this._lienRemunerationRevenuComplementaireSet)
			this._lienRemunerationRevenuComplementaireSet = new java.util.HashSet();
		this._lienRemunerationRevenuComplementaireSet.add(obj);
	}

	@Override
	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof com.cci.gpec.db.base.BaseRemuneration))
			return false;
		else {
			com.cci.gpec.db.base.BaseRemuneration mObj = (com.cci.gpec.db.base.BaseRemuneration) obj;
			if (null == this.getIdRemuneration()
					|| null == mObj.getIdRemuneration())
				return false;
			else
				return (this.getIdRemuneration().equals(mObj
						.getIdRemuneration()));
		}
	}

	@Override
	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdRemuneration())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getIdRemuneration().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	@Override
	public String toString() {
		return super.toString();
	}

	public Double getBaseBruteAnnuelle() {
		return baseBruteAnnuelle;
	}

	public void setBaseBruteAnnuelle(Double baseBruteAnnuelle) {
		this.baseBruteAnnuelle = baseBruteAnnuelle;
	}

	public Double getRemuGlobale() {
		return remuGlobale;
	}

	public void setRemuGlobale(Double remuGlobale) {
		this.remuGlobale = remuGlobale;
	}

	public Double getHeuresSupAnnuelles() {
		return heuresSupAnnuelles;
	}

	public void setHeuresSupAnnuelles(Double heuresSupAnnuelles) {
		this.heuresSupAnnuelles = heuresSupAnnuelles;
	}

	public Double getAvantagesNonAssujettisAnnuels() {
		return avantagesNonAssujettisAnnuels;
	}

	public void setAvantagesNonAssujettisAnnuels(
			Double avantagesNonAssujettisAnnuels) {
		this.avantagesNonAssujettisAnnuels = avantagesNonAssujettisAnnuels;
	}

}