package com.cci.gpec.db.base;

import java.io.Serializable;

/**
 * This class has been automatically generated by Hibernate Synchronizer. For
 * more information or documentation, visit The Hibernate Synchronizer page at
 * http://www.binamics.com/hibernatesync or contact Joe Hudson at
 * joe@binamics.com.
 * 
 * This is an object that contains data related to the MOTIFRUPTURECONTRAT
 * table. Do not modify this class because it will be overwritten if the
 * configuration file related to this class is modified.
 * 
 * @hibernate.class table="MOTIFRUPTURECONTRAT"
 */
public abstract class BaseMotifrupturecontrat implements Serializable {

	public static String PROP_NOM_TYPE_RECOURS = "NomMotifRuptureContrat";
	public static String PROP_ID = "Id";

	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _nomMotifRuptureContrat;
	private java.lang.Integer ordreAffichage;

	// collections
	private java.util.Set _pARCOURSs;

	// constructors
	public BaseMotifrupturecontrat() {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMotifrupturecontrat(java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize() {
	}

	/**
	 * Return the unique identifier of this class
	 * 
	 * @hibernate.id generator-class="identity" column="ID_TYPE_RECOURS"
	 */
	public java.lang.Integer getId() {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * 
	 * @param _id
	 *            the new ID
	 */
	public void setId(java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
	 * Return the value associated with the column: MOTIF_RUPTURE_CONTRAT
	 */
	public java.lang.String getNomMotifRuptureContrat() {
		return _nomMotifRuptureContrat;
	}

	/**
	 * Set the value related to the column: NOM_MOTIF_RUPTURE_CONTRAT
	 * 
	 * @param _nomMotifRuptureContrat
	 *            the NOM_MOTIF_RUPTURE_CONTRAT value
	 */
	public void setNomMotifRuptureContrat(
			java.lang.String _nomMotifRuptureContrat) {
		this._nomMotifRuptureContrat = _nomMotifRuptureContrat;
	}

	/**
	 * Return the value associated with the column: PARCOURSs
	 */
	public java.util.Set getPARCOURSs() {
		return this._pARCOURSs;
	}

	/**
	 * Set the value related to the column: PARCOURSs
	 * 
	 * @param _pARCOURSs
	 *            the PARCOURSs value
	 */
	public void setPARCOURSs(java.util.Set _pARCOURSs) {
		this._pARCOURSs = _pARCOURSs;
	}

	public void addToPARCOURSs(Object obj) {
		if (null == this._pARCOURSs)
			this._pARCOURSs = new java.util.HashSet();
		this._pARCOURSs.add(obj);
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof BaseMotifrupturecontrat))
			return false;
		else {
			BaseMotifrupturecontrat mObj = (BaseMotifrupturecontrat) obj;
			if (null == this.getId() || null == mObj.getId())
				return false;
			else
				return (this.getId().equals(mObj.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":"
						+ this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public String toString() {
		return super.toString();
	}

	public java.lang.Integer getOrdreAffichage() {
		return ordreAffichage;
	}

	public void setOrdreAffichage(java.lang.Integer ordreAffichage) {
		this.ordreAffichage = ordreAffichage;
	}

}